// From drivers/usb/gadget/rockhopper.c
typedef enum {
  RH_CONFIG_SENTINEL,
  RH_CONFIG_UMS,
  RH_CONFIG_UMS_NOVACOM,
  RH_CONFIG_PASSTHRU,
  RH_CONFIG_USBNET_PASSTHRU,
  RH_CONFIG_USBNET_UMS_NOVACOM,
  RH_CONFIG_PASSTHRU_NOVACOM
} USB_STATE;
