#!/bin/sh

PID="org.webosinternals.freetether"

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Stop the service if running
/usr/bin/killall -9 ${PID} || true

# Remove the freetether executable
rm -f /var/usr/sbin/${PID}

# Remove the dbus service
rm -f /var/palm/system-ervices/${PID}.service

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/pub/${PID}.json
rm -f /var/palm/ls2/roles/prv/${PID}.json

exit 0
